
// eslint-disable-next-line import/no-anonymous-default-export
export  default [
  {
    title: 'DevsFood',
    img: '/assets/devsfood.png',
    imgmodal: '/assets/courses-b7web.svg',
    description: "Aplicação que conecta prestadores de serviço (Barbeiros e Cabeleireiros) aos clientes em suas regiões. Aplicação montada durante o bootcamp GoStack aplicando todo o conhecimento adquirido durante a jornada. Neste projeto foi utilizada as melhores práticas na construção do projeto, com o uso das tecnologias TypeScript, Express, TypeORM em cima do Ambiente e execução de javascript, o NodeJS.",
    descriptiontools: 'Aplicação foi criada com React, React Native + Typescript, Node(Express), Postgres, Docker.',
    url: "https://github.com/EduardoMoreira26/GoBarber",
    site: "",
    nameurl : "Repositório GitHub",
    tecnology : "React, Node, ReactNative",
  },
  {
    title: 'GoBarber',
    img: '/assets/gobarber.svg',
    imgmodal: '/assets/gobarber.svg',
    description: "Aplicação que conecta prestadores de serviço (Barbeiros e Cabeleireiros) aos clientes em suas regiões. Aplicação montada durante o bootcamp GoStack aplicando todo o conhecimento adquirido durante a jornada. Neste projeto foi utilizada as melhores práticas na construção do projeto, com o uso das tecnologias TypeScript, Express, TypeORM em cima do Ambiente e execução de javascript, o NodeJS.",
    descriptiontools: 'Aplicação foi criada com React, React Native + Typescript, Node(Express), Postgres, Docker.',
    url: "https://github.com/EduardoMoreira26/GoBarber",
    site: "",
    nameurl : "Repositório GitHub",
    tecnology : "React, Node, ReactNative",
  },
  {
    title: 'Go Finances',
    img: '/assets/courses-b7web.svg',
    imgmodal: '/assets/courses-b7web.svg',
    description: "Este é um projeto de próposito didático foi desenvolvido durante o Bootcamp GoStack 11 da Rocketseat. Essa é uma aplicação de finanças que lista transações financeiras de entrada e saída, permitindo o upload de novas transações através da importação de arquivos CSV. Foi criado o Frontend com React e o backend com Node (Express).",
    descriptiontools: 'Aplicação foi criada com React + Typescript, React Router, estilizado com styled-components, Axios para estabelecer a conexão com API.',
    url: "https://github.com/EduardoMoreira26/GoFinances-FrontEnd",
    site: "",
    nameurl : "Repositório GitHub",
    tecnology : "React, Node(Express) + Typescript",
  },
   {
     title: 'Olx Clone',
     img: '/assets/olx.svg',
     imgmodal: '/assets/olx.svg',
     description: "Projeto criado com principal objetivo de colocar em prática todo o conhecimento adquirido no curso da plataforma B7WEB, onde foi abordado todos os conceitos da biblioteca React. Neste projeto o usuário pode se cadastrar e fazer login com uma conta já cadastrada. É possível criar um anúncio se o usuário estiver logado e preenchido os campos obrigatórios. Os anúncios podem ser filtrados pelo nome do que procura, estado e categorias.",
     descriptiontools: 'Aplicação criada com React e style-components foi utilizado para fazer a estilização do projeto. Possui controle de rotas, validação de campos, pagina de erro, Login, Cadastro, Home, Rota Privada,',
     url: "https://github.com/EduardoMoreira26/FrontEnd-OLX",
     site: "",
     nameurl : "Repositório GitHub",
     tecnology : "React",
   },
   {
     title: 'Ecoleta',
     img: '/assets/courses-b7web.svg',
     imgmodal: '/assets/courses-b7web.svg',
     description: "O projeto tem como finalidade estabelecer uma conexão entre empresas e/ou entidades que coletam resíduos (orgânicos e inorgânicos) às pessoas e/ou entidades que necessitam constantemente descartar esses resíduos. Solucionando um grande problema recorrente que é o descarte inadequado do lixo, facilitando o processo de recliclagem e reutilização.",
     descriptiontools: 'Aplicação criada com React + Typescript, e foi utilizada o Axios para estabelecer a conexão com API, na aplicação o mapa utilizado foi o Leaflet, style-components foi utilizado para fazer a estilização do projeto.',
     url: "https://github.com/EduardoMoreira26/NLW-Ecoleta-FrontEnd",
     site:  "",
     tecnology : "React + Typescript",

   },
   {
     title: 'GitHub Explorer',
     img: '/assets/courses-jstack.svg',
     imgmodal: '/assets/courses-jstack.svg',
     description: "Projeto criado com o objetivo de praticar os fundamentos do ReactJs. Com requisições da API do GitHub onde é possível pesquisasr e listar repositórios dos usuários, mostrando suas issues.",
     descriptiontools: 'Aplicação foi criada com React + Typescript, React Router, estilizado com styled-components, e localStorage para manter os dados pesquisados quando sair da página.',
     url: "https://github.com/EduardoMoreira26/Github-Explorer",
     site: "https://githubrepositoryexplorer.netlify.app/",
     nameurl : "Repositório GitHub",
     tecnology : "React + Typescript",

   },
   {
    title: 'Animais Fantásticos',
    img: '/assets/courses-rocket.svg',
    imgmodal: '/assets/courses-rocket.svg',
    description: "Projeto criado com o intuito de práticar o JS puro sem a utilização de plugins, o projeto conta com animações como scroll suave, accordeon, dropmenu, toolltip e mais. No projeto consolidei conceitos na prática como JS assíncrono, classes, operadores Rest e Spread, manipulação da DOM, destructuring, regular expressions, manipular a API Web Storage",
    descriptiontools: 'Aplicação foi criada com HTML, CSS Grid, CSS Flexbox, JS Vanilla.',
    url: "https://github.com/EduardoMoreira26/Animais-Fantasticos--Site",
    site: "",
    nameurl : "Repositório GitHub",
    tecnology : "HTML, CSS Grid Flexbox, JS Vanilla",

  },
  
  {
    title: 'FlexBlog',
    img: '/assets/courses-b7web.svg',
    imgmodal: '/assets/courses-b7web.svg',
    description: "Aplicação criada com intuito de colocar em prática os estudos de CSS Flexbox, ferramenta muito prática que trás de forma simples e prática uma responsividade para o projeto.",
    descriptiontools: 'Site foi criado utilizando HTML, CSS Flexbox',
    url: "https://github.com/EduardoMoreira26/FlexBlog",
    site: "https://edumoreiradev.netlify.app/",
    tecnology : "HTML, CSS Flexbox",

  },
  {
    title: 'Bikcraft',
    img: '/assets/bikcraft.png',
    imgmodal: '/assets/courses-origamid.svg',
    description: "Projeto desenvolvido no curso de Web Design da Plataforma de ensino Origamid.",
    descriptiontools: 'Site criado com HTML, CSS e JS.',
    url: "https://github.com/EduardoMoreira26/Bikcraft",
    site: "https://sitebike.netlify.app/",
    tecnology : "HTML, CSS & JS",
  },
  
 ]